### ISSUE TITLE
WebApp studenten krijgen de actieve vraag gepusht

### ISSUE THREAD

**Issue by Rival-Thompson** [Rival-Thompson/CloudApplications-TeachMe#26]
# Algemene omschrijving:

Als de docent een bepaald type vraag actief maakt krijgt de student deze vraag doorgepusht en kan hij deze lezen/bekijken met alle opties voor dat type vraag.
# Onderlinge Taken:
## Open vraag gepusht
- [x] Web UI aanmaken (html +css)
- [x] Backend / functionaliteit voorzien
- [x] Testen geheel
## Code vraag gepusht
- [x] Web UI aanmaken (html +css)
- [x] Backend / functionaliteit voorzien
- [x] Testen geheel
## Multiple-Choice vraag gepusht
- [x] Web UI aanmaken (html +css)
- [x] Backend / functionaliteit voorzien
- [x] Testen geheel
